version: '3.3'
services:
  db:
    image: mariadb
    restart: always
    env_file:
      - 'docker.env'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql
volumes:
  my-db: